### ISSUE TITLE
StuffCategory lacks a null check

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/Rimworld-SurvivalTools-old#1]
Short description: When loading mods that add StuffCategory by xml patch (e.g. Pelador's rimplas+medical supplements) you get a start-up error.

[BetterLoading] Exception occurred processing mod finalize events! Details: System.TypeInitializationException: The type initializer for 'SurvivalTools.StaticConstructorClass' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object

Steps to reproduce:
1) Add the mods above in any load order

Notes: The code in question is probably:

https://github.com/Jellypowered/SurvivalTools/blob/02caa05c3b712e1d60a65483b56480ee30648347/Source/SurvivalTools/StaticConstructorClass.cs#L81-L85

There lacks a check if Null before requesting StuffCategory attribute. Sorry I haven't had time to confirm it, thus the opening of the issue.

**Comment by Jellypowered** [comment]
I've merged your proposed commit that deals with this, thanks for the help :)
