### ISSUE TITLE
Misc Robots++ Compatibility

### ISSUE THREAD

**Issue by ridesdragons** [LecrisUT/Rimworld-SurvivalTools-old#10]
Roombas can't equip tools (unlike real life where they often equip knives and guns). Because of this when using Misc Robots++, which adds builder bots (which can mine) and kitchen bots (which can farm), they suffer from reduced yield and speed. normally I wouldn't think a robot that's designed to build and dig wouldn't come with a built-in hammer and drill (the higher tier ones have a visible drill, to boot).

can you make it so robots from misc robots++ do not suffer from reduced speed/yield due to not having tools?

**Comment by LecrisUT** [comment]
I'll test it. It shouldn't be a hard fix. From what I've seen in the code it should already have a check for that, but I'll see why it's not triggered

**Comment by Jellypowered** [comment]
I had noticed this was a bug in XND's release as well. Noted.

**Comment by LecrisUT** [comment]
We should discuss this: It seems Misc Robots++ has been abandoned, so there might be an increasing number of bugs as time goes on. It is a purely `xml` mod so maybe someone can pick it up :D . I think people will still use this mod, so I will make a patch for it anyway.

**Comment by LecrisUT** [comment]
@ridesdragons The patch was made. Expect it in the new release.
Thank you for your contribution.

**Comment by ridesdragons** [comment]
oh, it's abandoned now? damn. I didn't notice that. hopefully it gets picked back up again by someone

**Comment by LecrisUT** [comment]
They said they don't want to delve into c#, but after messing around with this mod, I'm confident I could fix whatever issues are with that mod. I have to figure out how to publish a mod on steam first.
