### ISSUE TITLE
Mod compability

### ISSUE THREAD

**Issue by Olsidian** [LecrisUT/Rimworld-SurvivalTools-old#26]
[Mod list length: 124]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Furniture Expanded - Art [https://steamcommunity.com/sharedfiles/filedetails/?id=1968134023]
Vanilla Animals Expanded — Australia [https://steamcommunity.com/sharedfiles/filedetails/?id=1963681588]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Vanilla Animals Expanded — Tropical Swamp [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283935]
Vanilla Animals Expanded — Tropical Rainforest [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283872]
Vanilla Animals Expanded — Ice Sheet [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364782]
Vanilla Animals Expanded — Tundra [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364585]
Vanilla Animals Expanded — Boreal Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364938]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Animals Expanded — Extreme Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849184079]
Vanilla Animals Expanded — Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849183875]
Vanilla Animals Expanded — Cats and Dogs [https://steamcommunity.com/sharedfiles/filedetails/?id=1823540489]
Vanilla Animals Expanded — Arid Shrubland [https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626]
VGP Three Sisters Plants [https://steamcommunity.com/sharedfiles/filedetails/?id=2007063848]
VGP Xtra Trees and Flowers [https://steamcommunity.com/sharedfiles/filedetails/?id=2007064094]
VGP More Veggies [https://steamcommunity.com/sharedfiles/filedetails/?id=2007063278]
VGP Garden Medicine [https://steamcommunity.com/sharedfiles/filedetails/?id=2007063140]
VGP Vegetable Garden [https://steamcommunity.com/sharedfiles/filedetails/?id=2007061826]
VGP Garden Gourmet [https://steamcommunity.com/sharedfiles/filedetails/?id=2007062982]
VGP Garden Fabrics [https://steamcommunity.com/sharedfiles/filedetails/?id=2007062162]
VGP Garden Canning [https://steamcommunity.com/sharedfiles/filedetails/?id=2007062033]
Humanoid Alien Races 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
Rimsenal - Enhanced Vanilla Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=849231601]
Dubs Bad Hygiene [https://steamcommunity.com/sharedfiles/filedetails/?id=836308268]
Rimefeller [https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735]
Alpha Animals [https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856]
Survival Tools Reborn [https://steamcommunity.com/sharedfiles/filedetails/?id=2017675890]
Dubs Mint Minimap [https://steamcommunity.com/sharedfiles/filedetails/?id=1662119905]
Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
Research Tree [https://steamcommunity.com/sharedfiles/filedetails/?id=1266570759]
The Birds and the Bees [https://steamcommunity.com/sharedfiles/filedetails/?id=751049133]
CM Color Coded Mood Bar [1.1] [https://steamcommunity.com/sharedfiles/filedetails/?id=2006605356]
More Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=846222458]
Damage Indicators [1.1] [https://steamcommunity.com/sharedfiles/filedetails/?id=2016331497]
Biomes! Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2038000893]
Biomes! Islands [https://steamcommunity.com/sharedfiles/filedetails/?id=2038001322]
Utility Columns [https://steamcommunity.com/sharedfiles/filedetails/?id=2013476665]
Smoked meat [https://steamcommunity.com/sharedfiles/filedetails/?id=1542364782]
Pygmy muffalo [https://steamcommunity.com/sharedfiles/filedetails/?id=1885527800]
SeedsPlease [https://steamcommunity.com/sharedfiles/filedetails/?id=935732834]
EdB Prepare Carefully [https://steamcommunity.com/sharedfiles/filedetails/?id=735106432]
Combat Extended Guns [https://steamcommunity.com/sharedfiles/filedetails/?id=1582570547]
Rimsenal + Combat Extended Compatibility Mega Patch [https://steamcommunity.com/sharedfiles/filedetails/?id=1940984629]
Androids [https://steamcommunity.com/sharedfiles/filedetails/?id=1541064015]
A Dog Said... Animal Prosthetics [https://steamcommunity.com/sharedfiles/filedetails/?id=746425621]
Giddy-up! Core [https://steamcommunity.com/sharedfiles/filedetails/?id=1216999901]
Giddy-up! Battle Mounts [https://steamcommunity.com/sharedfiles/filedetails/?id=1217001091]
Giddy-up! Ride and Roll [https://steamcommunity.com/sharedfiles/filedetails/?id=1331961995]
Giddy-up! Caravan [https://steamcommunity.com/sharedfiles/filedetails/?id=1253251478]
Megafauna [https://steamcommunity.com/sharedfiles/filedetails/?id=1055485938]
Royal Thrumbos [https://steamcommunity.com/sharedfiles/filedetails/?id=1865990377]
Android tiers [https://steamcommunity.com/sharedfiles/filedetails/?id=1386412863]
Beetle People [https://steamcommunity.com/sharedfiles/filedetails/?id=1504654099]
The Drow Race Continued [https://steamcommunity.com/sharedfiles/filedetails/?id=2012718526]
Vanilla Armour Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282]
Nature's Pretty Sweet [https://steamcommunity.com/sharedfiles/filedetails/?id=1211694919]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
Sand Castles [https://steamcommunity.com/sharedfiles/filedetails/?id=1980394843]
Vanilla Apparel Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817]
Glass+Lights [https://steamcommunity.com/sharedfiles/filedetails/?id=826153738]
Dubs Skylights [https://steamcommunity.com/sharedfiles/filedetails/?id=833899765]
Fertile Fields [1.1] [https://steamcommunity.com/sharedfiles/filedetails/?id=2012735237]
Dubs Skylights Glass+Lights Patch [https://steamcommunity.com/sharedfiles/filedetails/?id=1610803364]
[FSF] Filth Vanishes With Rain And Time [https://steamcommunity.com/sharedfiles/filedetails/?id=1508341791]
Pick Up And Haul [https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058]
Search and Destroy [https://steamcommunity.com/sharedfiles/filedetails/?id=1467764609]
RunAndGun [https://steamcommunity.com/sharedfiles/filedetails/?id=1204108550]
TechSales [https://steamcommunity.com/sharedfiles/filedetails/?id=1935360087]
More Inspiration Types [https://steamcommunity.com/sharedfiles/filedetails/?id=2019094541]
P-Music [https://steamcommunity.com/sharedfiles/filedetails/?id=725130005]
CleaningArea [https://steamcommunity.com/sharedfiles/filedetails/?id=870089952]
[1.1] Psychology (unofficial) [https://steamcommunity.com/sharedfiles/filedetails/?id=2016263135]
Dynamic Diplomacy [https://steamcommunity.com/sharedfiles/filedetails/?id=1875168898]
SeedsPleaseDrawingsPatch [https://steamcommunity.com/sharedfiles/filedetails/?id=2022152089]
Nature is Beautiful [1.0][1.1] [https://steamcommunity.com/sharedfiles/filedetails/?id=2039219077]
[1.1] Defenses Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1550972678]
Combat Extended Melee [https://steamcommunity.com/sharedfiles/filedetails/?id=1924933379]
[1.1] Ceramics [https://steamcommunity.com/sharedfiles/filedetails/?id=1833163132]
[1.1] Combat Extended: Shields [https://steamcommunity.com/sharedfiles/filedetails/?id=1586351220]
Auto-Cut Blight [https://steamcommunity.com/sharedfiles/filedetails/?id=1885186534]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Hospitality [https://steamcommunity.com/sharedfiles/filedetails/?id=753498552]
Medical Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=715565817]
Expanded Prosthetics and Organ Engineering [https://steamcommunity.com/sharedfiles/filedetails/?id=725956940]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
Snap Out! [https://steamcommunity.com/sharedfiles/filedetails/?id=1319782555]
Real Ruins [https://steamcommunity.com/sharedfiles/filedetails/?id=1552146295]
[KV] Faction Control - 1.1 [https://steamcommunity.com/sharedfiles/filedetails/?id=1509102551]
Smart Speed [https://steamcommunity.com/sharedfiles/filedetails/?id=1504723424]
[1.1] Wild Animal Sex V5.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=1224175982]
Animal Gear [https://steamcommunity.com/sharedfiles/filedetails/?id=1541438907]
Animal Armor: Vanilla [https://steamcommunity.com/sharedfiles/filedetails/?id=1743423205]
Animal Gear Basic [https://steamcommunity.com/sharedfiles/filedetails/?id=1541439112]
Faction Blender [https://steamcommunity.com/sharedfiles/filedetails/?id=1734490820]
Mantis race [https://steamcommunity.com/sharedfiles/filedetails/?id=2025343753]
Boomaphants 1.1 [https:// no link (local mod)]
Gradient Hair [https://steamcommunity.com/sharedfiles/filedetails/?id=1687053679]
Autocleaner [https:// no link (local mod)]
Set Owner for Prisoner Beds [https:// no link (local mod)]
Jelly Farm 1.1 [https://steamcommunity.com/sharedfiles/filedetails/?id=1363721847]
RPG Style Inventory CE Revived [1.0+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2009087797]
MineItAll - unofficial [https://steamcommunity.com/sharedfiles/filedetails/?id=1204987547]
[SYR] Set Up Camp [https://steamcommunity.com/sharedfiles/filedetails/?id=1470065926]
Conduit Deconstruct [https://steamcommunity.com/sharedfiles/filedetails/?id=838336462]
Gear Up And Go [https://steamcommunity.com/sharedfiles/filedetails/?id=1316142788]
TD Enhancement Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=1339135272]
Everybody Gets One [https://steamcommunity.com/sharedfiles/filedetails/?id=1687566130]
Hardworking animals 1.1 [https://steamcommunity.com/sharedfiles/filedetails/?id=933324235]
Simply More Bridges (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2012484790]
While You're Up (Continued)[1.1] [https://steamcommunity.com/sharedfiles/filedetails/?id=2009351077]
RimPy Mod Manager Database [https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158]
Large Animal Beds [https://steamcommunity.com/sharedfiles/filedetails/?id=1111387020]
Caravan Gear [1.1] [https://steamcommunity.com/sharedfiles/filedetails/?id=2018290315]

**Comment by LecrisUT** [comment]
You have to be a bit more specific there bud. Is there:
- An incompatibility giving red error?
- A lack of compatibility with a mod, lack of functionality, feature?
- Something else entirely?

**Comment by Olsidian** [comment]
This mod works with this list of mods. But the list of errors goes out, without the participation of the mod on tools

**Comment by Olsidian** [comment]
Now I will copy the red errors. But they don't seem to belong to this mod.

**Comment by LecrisUT** [comment]
So you get error without this mod, but with this mod you do not? If you know how to post HugsLib log, please do.

**Comment by Olsidian** [comment]
[[1.1] Ceramics] Patch operation Verse.PatchOperationFindMod(Combat Extended) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\1833163132\Patches\Combat Extended\Patch_CombatExtended.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by Olsidian** [comment]
Could not resolve cross-reference to Verse.ThingDef named N7_Sand (wanter=thingDefs)
Verse.Log:Error(String, Boolean)
Verse.DirectXmlCrossRefLoader:TryResolveDef(String, FailMode, Object)
Verse.WantedRefForList`1:TryResolve(FailMode)
Verse.<>c__DisplayClass14_1:<ResolveAllWantedCrossReferences>b__0(WantedRef)
Verse.<>c__DisplayClass6_1`1:<ParallelForEach>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

**Comment by Olsidian** [comment]
Mod RimPy Mod Manager Database did not load any content. Following load folders were used:
  - C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\1847679158
Verse.Log:Error(String, Boolean)
Verse.<>c:<LoadModContent>b__13_1()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:DMD<DMD<Update_Patch1>?100246528::Update_Patch1>(Root)
Verse.Root_Entry:Update()

**Comment by Olsidian** [comment]
Failed to find any textures at Things/Pawn/Animal/Wildebeest/Wildebeest_Wildebeest while constructing Multi(initPath=Things/Pawn/Animal/Wildebeest/Wildebeest_Wildebeest, color=RGBA(1.000, 1.000, 1.000, 1.000), colorTwo=RGBA(1.000, 1.000, 1.000, 1.000))
Verse.Log:Error(String, Boolean)
Verse.Graphic_Multi:Init(GraphicRequest)
Verse.GraphicDatabase:GetInner(GraphicRequest)
Verse.GraphicDatabase:Get(Type, String, Shader, Vector2, Color, Color, GraphicData, List`1)
Verse.GraphicData:Init()
Verse.GraphicData:get_Graphic()
CombatExtended.BoundsInjector:Inject()
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:DMD<DMD<Update_Patch1>?100246528::Update_Patch1>(Root)
Verse.Root_Entry:Update()

**Comment by Olsidian** [comment]
Exception from long event: System.Exception: AEXP_Wildebeest.lifeStages[1].femaleDessicatedBodyGraphicData ---> System.Exception: BoundMap(,) ---> System.Exception: Combat Extended :: CropVertical error while cropping Textures/Things/Pawn/Animal/Wildebeest/Wildebeest_Wildebeest_side ---> System.NullReferenceException: Object reference not set to an instance of an object
  at CombatExtended.BoundsInjector.ExtractBounds (Verse.Graphic graphic, CombatExtended.BoundsInjector+GraphicType type) [0x00006] in <51a637428c0449319bfa1366f15a6d64>:0 
   --- End of inner exception stack trace ---
  at CombatExtended.BoundsInjector.ExtractBounds (Verse.Graphic graphic, CombatExtended.BoundsInjector+GraphicType type) [0x00041] in <51a637428c0449319bfa1366f15a6d64>:0 
  at CombatExtended.BoundsInjector.BoundMap (Verse.Graphic graphic, CombatExtended.BoundsInjector+GraphicType type) [0x00012] in <51a637428c0449319bfa1366f15a6d64>:0 
   --- End of inner exception stack trace ---
  at CombatExtended.BoundsInjector.BoundMap (Verse.Graphic graphic, CombatExtended.BoundsInjector+GraphicType type) [0x00037] in <51a637428c0449319bfa1366f15a6d64>:0 
  at CombatExtended.BoundsInjector.Inject () [0x00190] in <51a637428c0449319bfa1366f15a6d64>:0 
   --- End of inner exception stack trace ---
  at CombatExtended.BoundsInjector.Inject () [0x001ca] in <51a637428c0449319bfa1366f15a6d64>:0 
  at Verse.LongEventHandler.UpdateCurrentSynchronousEvent (System.Boolean& sceneChanged) [0x0001d] in <c8e8d421567e4ee5864626a429a27a37>:0 
Verse.Log:Error(String, Boolean)
Verse.LongEventHandler:UpdateCurrentSynchronousEvent(Boolean&)
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:DMD<DMD<Update_Patch1>?100246528::Update_Patch1>(Root)
Verse.Root_Entry:Update()

**Comment by LecrisUT** [comment]
Please post HugsLib log. [Ctrl+F12] and follow the instructions. It is quite hard to decipher in this format.

The first problem I can think of is that I have removed the compatibility with CombatExtended for now. You have various other problems that are not caused by this mod.

**Comment by Olsidian** [comment]
https://gist.github.com/39ddffd2ac5c58f9502ce97e2226eb6d

**Comment by LecrisUT** [comment]
So is this log for the problem of the tools gone missing? At first glance I do not see any obvious error messages.

It will help tremendously if you could narrow down what is causing your problem. Using rimpy, remove chunks of 5-15 mods you belive are irrelevant or just at random, until you find the relevant ones. 

A few other things. Rimpy does not need to be loaded in your active mod list to work. Turning on devmode and quickstart (I think rightmost icon at the top) can speed up the debugging. 

Btw there's a new version of the mod. Check the steam comments.

**Comment by Olsidian** [comment]
Now there is no problem, the mod works

**Comment by LecrisUT** [comment]
Ok. If there are any other problems, feel free to post.
