### ISSUE TITLE
Yellow Warnings About JobDriver

### ISSUE THREAD

**Issue by ghost** [LecrisUT/Rimworld-SurvivalTools-old#27]
Tested on game version 1.1.2598, with the Royalty DLC.
Tested on your Initial Rebirth: V2.3.0 (Update: 12 Apr). 
Same errors happen even on the previous Jellypowered's version (Update: 6 Apr). 

I'm getting these three yellow warnings: 
(Moving the mod around the load order doesn't fix it.)

[Lecris.survivaltoolsreborn][warn] Couldn't backtrack jobDriver patch: CompInstalledPart.JobDriver_InstallPart => Verse.AI.JobDriver
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Lecris.survivaltoolsreborn][warn] Couldn't backtrack jobDriver patch: CompInstalledPart.JobDriver_UninstallPart => Verse.AI.JobDriver
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

[Lecris.survivaltoolsreborn][warn] Couldn't backtrack jobDriver patch: CompVehicle.JobDriver_AssembleVehicle => Verse.AI.JobDriver
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

**Comment by LecrisUT** [comment]
Thank you, i remember those warnings, forgot to look intoit. Can you upload hugslib log or the section where it says [Lecris.SurvivalToolsreborn] autopatch or stats patched? (forgot which). Should be near the bottom.

**Comment by ghost** [comment]
Sure, here's the section. And not sure if it matters, but here are all the mods I'm currently running that your mod has patches for: Alpha Animals, Mending (Mend And Recycle), Vegetable Garden and Vanilla Weapons Expanded.

[Lecris.survivaltoolsreborn] Stats auto patched:

Patch : MiningSpeed => MiningSpeed_Tool
JobDrivers:
 [ True | True ] RimWorld.JobDriver_Mine :: ! Void ResetTicksToPickHit() ! : Void <MakeNewToils>b__0() 

JobDefs:
 Mine : Verse.JobDef Mine

WorkGivers:
RimWorld.WorkGiver_Miner :: Methods :: Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) :: Properties ::: Fields :

Patch : MiningYield => MiningYield_Tool
JobDrivers:
 [ True | False ] RimWorld.Mineable :: Void Notify_TookMiningDamage(Int32, Verse.Pawn) 

JobDefs:

WorkGivers:

Patch : ConstructionSpeed => ConstructionSpeed_Tool
JobDrivers:
 [ True | True ] RimWorld.JobDriver_RemoveFloor :: ! RimWorld.StatDef get_SpeedStat() ! : Void <MakeNewToils>b__2() 
 [ False | True ] RimWorld.JobDriver_AffectRoof :: Void <MakeNewToils>b__1() 
 [ False | True ] RimWorld.JobDriver_ConstructFinishFrame :: Void <MakeNewToils>b__1() 
 [ False | True ] RimWorld.JobDriver_RemoveBuilding :: Void <MakeNewToils>b__1() 
 [ False | True ] RimWorld.JobDriver_Repair :: Void <MakeNewToils>b__1() 
 [ True | False ] CompInstalledPart.JobDriver_InstallPart :: ! Void <MakeNewToils>b__15_2() ! 
 [ True | False ] CompInstalledPart.JobDriver_UninstallPart :: ! Void <MakeNewToils>b__15_2() ! 
 [ True | False ] CompVehicle.JobDriver_AssembleVehicle :: ! Void <MakeNewToils>b__12_2() ! 
 [ False | True ] TurretExtensions.JobDriver_UpgradeTurret :: Void <Upgrade>b__0() 
 [ False | True ] RemoteTech.JobDriver_InstallUpgrade :: Void <MakeNewToils>b__5() 
 [ False | True ] Autocleaner.JobDriverRepairAutocleaner :: Void <MakeNewToils>b__0() 
 [ False | True ] SandCastleMod.JobDriver_BuildSandCastle :: Void <MakeNewToils>b__1() 

JobDefs:
 FinishFrame : Verse.JobDef FinishFrame
 Deconstruct : Verse.JobDef Deconstruct
 Uninstall : Verse.JobDef Uninstall
 Repair : Verse.JobDef Repair
 BuildRoof : Verse.JobDef BuildRoof
 RemoveRoof : Verse.JobDef RemoveRoof
 RemoveFloor : Verse.JobDef RemoveFloor
 RemoveThickRoof : Verse.JobDef RemoveThickRoof
 UpgradeTurret : Verse.JobDef UpgradeTurret
 rxInstallUpgrade : Verse.JobDef rxInstallUpgrade
 AutocleanerRepair : Verse.JobDef AutocleanerRepair

WorkGivers:
RimWorld.WorkGiver_BuildRoof :: Methods :: Verse.AI.Job JobOnCell(Verse.Pawn, Verse.IntVec3, Boolean) :: Properties ::: Fields :
RimWorld.WorkGiver_ConstructRemoveFloor :: Methods :: Verse.AI.Job JobOnCell(Verse.Pawn, Verse.IntVec3, Boolean) :: Properties ::: Fields :
RimWorld.WorkGiver_ConstructDeliverResources :: Methods :: Verse.AI.Job RemoveExistingFloorJob(Verse.Pawn, RimWorld.Blueprint) :: Properties ::: Fields :
RimWorld.WorkGiver_ConstructFinishFrames :: Methods :: Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) :: Properties ::: Fields :
RimWorld.WorkGiver_Deconstruct :: Methods :: Verse.JobDef get_RemoveBuildingJob() :: Properties ::: Fields :
RimWorld.WorkGiver_RemoveRoof :: Methods :: Verse.AI.Job JobOnCell(Verse.Pawn, Verse.IntVec3, Boolean) :: Properties ::: Fields :
RimWorld.WorkGiver_Uninstall :: Methods :: Verse.JobDef get_RemoveBuildingJob() :: Properties ::: Fields :
RimWorld.WorkGiver_Repair :: Methods :: Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) :: Properties ::: Fields :
TerraformRimworld.WorkGiver_RemoveThickRoof :: Methods :: Verse.AI.Job JobOnCell(Verse.Pawn, Verse.IntVec3, Boolean) :: Properties ::: Fields :
TurretExtensions.WorkGiver_UpgradeTurret :: Methods :: Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) :: Properties ::: Fields :
RemoteTech.WorkGiver_InstallUpgrade :: Methods :: Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) :: Properties ::: Fields :
Autocleaner.WorkGiverRepairAutocleaner :: Methods :: Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) :: Properties ::: Fields :

Patch : PlantWorkSpeed => PlantWorkSpeed_Harvesting_Tool
JobDrivers:
 [ False | True ] RimWorld.JobDriver_PlantWork :: Void <MakeNewToils>b__1() 

JobDefs:
 Harvest : Verse.JobDef Harvest
 HarvestDesignated : Verse.JobDef HarvestDesignated
 CutPlant : Verse.JobDef CutPlant
 CutPlantDesignated : Verse.JobDef CutPlantDesignated

WorkGivers:
RimWorld.WorkGiver_GrowerHarvest :: Methods :: Verse.AI.Job JobOnCell(Verse.Pawn, Verse.IntVec3, Boolean) :: Properties ::: Fields :
RimWorld.WorkGiver_PlantsCut :: Methods :: Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) : Verse.AI.Job JobOnThing(Verse.Pawn, Verse.Thing, Boolean) :: Properties ::: Fields :

[Lecris.survivaltoolsreborn] Other Patches:
Race exemption list: (I know how it sounds, but it's not racist ><)

**Comment by LecrisUT** [comment]
That is exactly what I needed, thanks.
Funny observation, pawns are using hammers to build sandcastles :)). I'll fix that.
Interesting, somehow your mod list has broken the main purpose of this autopatch: to not require hammers to deliver stuff. Please send the list of mods as well.

Note to self: find which mod uses namespace: CompVehicle, etc.
Reply to self: It's JecsTools.

**Comment by ghost** [comment]
https://gist.github.com/4ac2967c63f612a0127bd433745102fb

Here's the link to the full log with all of my mods loaded (215 in total). And a fair warning, I added my own custom tags and changed the names for most of the mods for my own convenience. I did pay attention to patches and made sure those were changed to match the new names as well.

For the sandcastle mod, it's this one:
https://steamcommunity.com/sharedfiles/filedetails/?id=1980394843

As for mods that specifically touch hauling, I'm using these two:
https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453
https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058

There's also ED Enhanced Options and Mehnis Modifications that offer some pawn fixes and quality of life improvements which might mess with hauling, but I'm not sure. There's also Awesome Inventory, an alternative of sorts to RPG Style Inventory, so I believe some patching will be required there. 

As far as I remember, I didn't get any additional errors from your mod during actual gameplay. 
And here's a few ideas that might give you some inspiration later down the line, while I'm at it:

- A crowbar, perhaps for faster deconstruction / construction of objects and structures exclusively made out of wood. Or like a combat tool that does extra damage to wooden material. Also so I can have a proper Mr Freeman running around in my game.
- A craftable toolbox of some sorts, that combines all of the tools together into one item and serves as a precursor / lower tech version of the Glitterworld Multitool. As colonists / pawns come and go, it gets somewhat tedious having to manage all of the tools in the early game.
- A tool /compatibility for the mod RimRoads, that makes the construction of roads faster. Or to make it so that some of the existing tools apply a faster construction bonus to roads.

Just some suggestions, your take on the Survival Tools is already awesome and greatly appreciated.  In any case, keep up the good work. By the way, all of the mods I'm using should be up to date.

**Comment by LecrisUT** [comment]
Thanks, I've almost finished patching up jectool. It proved my expectations wrong, so I had to rewrite my autopatch implementation.

Thank you for pointing out those mods, it helps a lot :-). Awesome inventory is already in the works, it will be hard that one, but I got 25% done.

I really like your ideas. Better roads should be an easy fix. The toolbox, how about a flat 100% workspeed? (I'm bad at balancing :-D). Crowbar on the other hand would be a bit difficult. I will think about it. Right now only crowbar, axe and sickle are specific to a subjob, if there will be more, I will implement a subjob specific.

**Comment by LecrisUT** [comment]
@IssueBro Sorry for the long delay, but I'm back to modding. I've fixed the original yellow warning, and added a patch for **Sand Castles**. I'm looking now at the hauling problem, and it doesn't seem to affect the need for tools, but I'll double check just in case.
