### ISSUE TITLE
Errors when Mod wants to drop tools.

### ISSUE THREAD

**Issue by Jellypowered** [LecrisUT/Rimworld-SurvivalTools-old#29]
I noticed this a couple times while I was working on the mod, but I could never figure it out. The error should be near the end of the log. 

https://gist.github.com/ecd56b9e2bc87d5f3ad125fb91bb0f28

**Comment by LecrisUT** [comment]
Yeah, I've noticed it too. There was no failsafe in XND's driver. I've added one based on `JobDriver_unloadyourinventory`. I'll push an update this weekend.

I'm also planning to rework how the inventory is tracked so pawns can hold excess tools, but periodically stow excess away.

**Comment by LecrisUT** [comment]
The recent commit should have fixed the issue. When you can, check how it is.
