### ISSUE TITLE
What to do with tools from other mods?

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/Rimworld-SurvivalTools-old#3]
Anyone who has ideas please pitch in.
Current mods which add redundant tools:
- Vanilla Weapons extended

**Comment by Jellypowered** [comment]
In theory because of how the code works, other tools from other mods get "grandfathered" in if they have compatibility patches.

**Comment by LecrisUT** [comment]
It's a bit annoying that we get duplicates. Since these tools have more functionality, maybe these should take the place of the other?
