### ISSUE TITLE
Harmony patches

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/Rimworld-SurvivalTools-old#6]
This scares me:
https://github.com/Jellypowered/SurvivalTools/blob/fbd81a25528da30b2ebe71638bc29a71faa60af8/Source/SurvivalTools/HarmonyPatches.cs#L190-L213

Was it written by XND, @Jellypowered or who? Shouldn't there be a more legible way to do the patch?

**Comment by Jellypowered** [comment]
The whole mod was written by XND. He lost interest/motivation to keep it updated and I asked if I could take over. Other than minor 1.1 compatibility, the code is largely still his. 

It shouldn't scare you, as it does at least work lol.

**Comment by LecrisUT** [comment]
I've found that other mods use harmony built-in transpiler, and it makes it much more readable. I'll put it on the list to rewrite these to be safer.

**Comment by LecrisUT** [comment]
Also, should make harmony as a mod dependency and reorganize the csproj, gitignore, etc.
