### ISSUE TITLE
Add industrial counterparts of tools (the middle step between multitool and early tools)

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/Rimworld-SurvivalTools-old#7]

**Comment by Jellypowered** [comment]
So currently the only thing not working with this contribution by Vova, is the chainsaw added does not count towards plant work. I'll have some time this weekend to get to debugging it.

**Comment by LecrisUT** [comment]
By design, chainsaw and axes do not count towards `plant cutting`. There are 2 workgivers now `fell tree` and `cut plant` to be used for `axe` and `sickle` respectively. If you toggle these workgivers individually it works fine.

So on my end everything works as it should.
