### ISSUE TITLE
`LTS degradation` also has degradation mechanics and  can overwrite vanilla:

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/Rimworld-SurvivalTools-old#8]
No conflicts in the mod, but we could integrate LTS's algorithm to decay depending on the quality

**Comment by Jellypowered** [comment]
How does this work compared to what is already in place? Does it work like the higher the quality the slower it degrades?

**Comment by LecrisUT** [comment]
It is customisable. Default is higher quality degrade less. Good news is there is no conflict with each other. Better news, we can easily trigger LTS's degradation instead of XND, and we get all those benefits ;-)
