### ISSUE TITLE
Add Primitive/Neolithic tools

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/Rimworld-SurvivalTools-old#9]
I think we should split the stone and metal tools in two. Primitive for only stone tools, and metal for the rest.

If so we can introduce more natural compatibility with other mods: E.g. Vanilla Weapons Expanded can replace the metallic tools and we patch survival tools properties to those.

The only thing is that we need some new graphics. Is anyone available for this?

**Comment by Jellypowered** [comment]
Graphics aren't my strong suit, but I'll ask around. :)

**Comment by LecrisUT** [comment]
I've asked Kasmex(Vladislav) over at Pelador's Discord for some graphics. @Jellypowered Can you implement them when he's made them?

**Comment by Jellypowered** [comment]
Pretty sure!
